name: SurvivalUtilities
version: '${project.version}'
main: de.thecoolcraft11.SurvivalUtilities
api-version: '1.20'
commands:
  chunkbase:
    aliases:
      - cb
    permission: survivalutilities.chunkbase
  survivalutilities:
    permission: survivalutilities.survivalutilities
  sudo:
    permission: survivalutilities.sudo
    description: Execute a command as an other player
  keepinventory:
    description: Toggles keepinventory for you
  blueprint:
    description: Create Blueprints
  save:
    description: Save a blueprint
  place:
    description: Place a saved blueprint
  jail:
    permission: survivalutilities.jail