name: SurvivalUtilities
version: '1.0-SNAPSHOT'
main: de.thecoolcraft11.SurvivalUtilities
api-version: '1.20'
commands:
  chunkbase:
    aliases:
      - cb
    permission: survivalutilities.chunkbase